version: '2.1'

services:
  # Frontend
  frontend:
    image: frontend
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TIER: frontend
        PORT: 8000
    ports:
      - "8000:8000"
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=8001
    links:
      - backend

  # Backend
  backend:
    image: backend
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TIER: backend
        PORT: 8001
    environment:
      - DB_URI=mongodb://database
    ports:
      - "8001:8001"
    links:
      - database

  # Database
  database:
    image: mongo:4.2
    container_name: database
    volumes:
      - ./db_data:/data
    ports:
      - "27017:27017"

  # Tests
  tests:
    image: postman/newman_alpine33
    container_name: tests-newman
    command: run --timeout 15000 --env-var URL=backend:8001 /tests/collection.json --bail
    volumes:
      - ./tests:/tests
    links:
      - backend
